fos_rest:
  routing_loader: false
  view:
    view_response_listener: "force"
    formats:
      json: true
      xml: true
  zone:
    - { path: "^/api" }
  format_listener:
    rules:
      - {
          path: "^/api/",
          priorities: ["json"],
          fallback_format: "json",
          prefer_extension: false,
        }
  body_listener:
    enabled: true
  param_fetcher_listener:
    enabled: true
  serializer:
    serialize_null: true
  exception:
    enabled: true
    map_exception_codes: true
    messages:
      'Symfony\Component\HttpKernel\Exception\HttpException': true
      'Symfony\Component\Security\Core\Exception\BadCredentialsException': true
    codes:
      'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
      'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401
      'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
      "LogicException": 500
      "InvalidArgumentException": 400
      "Exception": 400
